# Generated by Django 2.1 on 2018-09-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
