# Generated by Django 2.1 on 2018-09-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='experpt',
            field=models.CharField(max_length=200),
        ),
    ]
